services:
  sict-bimini-web:
    build:
      context: .
    image: python3.14.2:trixie-slim-uv-bun
    container_name: sict-bimini-web
    tty: true
    ipc: host
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/sict-bimini-web
      - /tmp/.X11-unix:/tmp/.X11-unix

  sict-bimini-web-gpu:
    extends:
      service: sict-bimini-web
    container_name: sict-bimini-web-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
